Fix undefined reference to `_Unwind_*` et al. when shared libgcc is built (#20)
`t-slibgcc` enables linking against shared libgcc.

(cherry picked from commit b98cbfefba1bd529639db57d4d032797aeee9a93)